from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProviderCredentialRepository(Protocol):
    """Model provider OAuth state와 token 참조를 durable하게 저장하는 경계다.

    실제 access token과 refresh token 원문은 DB row가 아니라 별도 secret 저장소에 두고,
    durable DB에는 재연결과 감사에 필요한 참조값과 비민감 metadata만 남긴다.
    """

    def create_provider_oauth_state(self, provider_name: str, state: str, redirect_uri: str, code_verifier: str | None = None) -> dict[str, Any]: ...
    def get_provider_oauth_state(self, provider_name: str, state: str) -> dict[str, Any] | None: ...
    def consume_provider_oauth_state(self, provider_name: str, state: str) -> dict[str, Any] | None: ...
    def delete_provider_oauth_states(self, provider_name: str) -> int: ...
    def upsert_provider_token(self, provider_name: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_provider_token(self, provider_name: str) -> dict[str, Any] | None: ...
    def delete_provider_token(self, provider_name: str) -> bool: ...
