from __future__ import annotations

from typing import Protocol


class GatewayPlatform(Protocol):
    async def connect(self, websocket) -> None: ...
    def disconnect(self, websocket) -> None: ...
    def subscribe(self, websocket, topic: str) -> None: ...
    async def broadcast(self, event: dict, topic: str) -> None: ...
