from __future__ import annotations

from typing import Protocol

from app.contracts.event.task_events import TaskEventEnvelope
from app.domain.tasks.models import StepRun, TaskRun


class TaskRepository(Protocol):
    def create_task(self, task: TaskRun) -> TaskRun: ...
    def update_task(self, task: TaskRun) -> TaskRun: ...
    def get_task(self, task_run_id: str) -> TaskRun | None: ...
    def list_tasks(self, *, status: str | None = None, limit: int = 20, offset: int = 0) -> list[TaskRun]: ...
    def count_tasks(self, *, status: str | None = None) -> int: ...
    def list_steps(self, task_run_id: str) -> list[StepRun]: ...
    def create_step(self, step: StepRun) -> StepRun: ...
    def update_step(self, step: StepRun) -> StepRun: ...
    def append_event(self, event: TaskEventEnvelope) -> TaskEventEnvelope: ...
    def list_events(self, task_run_id: str) -> list[TaskEventEnvelope]: ...
    def create_approval_request(self, task_run_id: str, step_run_id: str, payload: dict) -> dict: ...
    def resolve_approval_request(self, approval_id: str, payload: dict) -> dict | None: ...
    def get_open_approval(self, task_run_id: str) -> dict | None: ...
