TASK_RUNS_TABLE = "task_runs"
STEP_RUNS_TABLE = "step_runs"
TASK_EVENTS_TABLE = "task_events"
APPROVAL_REQUESTS_TABLE = "approval_requests"
PROVIDER_OAUTH_STATES_TABLE = "provider_oauth_states"
PROVIDER_TOKENS_TABLE = "provider_tokens"
