from __future__ import annotations

from typing import Any, Protocol

from app.domain.work.models import WorkComment, WorkItem, WorkLabel, WorkRunLink, WorkStatus


class WorkRepository(Protocol):
    def next_identifier(self, session_id: str) -> str: ...

    def create_work(self, work: WorkItem, *, client_request_id: str | None = None) -> WorkItem: ...

    def get_work(self, work_id: str) -> WorkItem | None: ...

    def get_work_by_identifier(self, session_id: str, identifier: str) -> WorkItem | None: ...

    def get_work_by_client_request_id(self, session_id: str, client_request_id: str) -> WorkItem | None: ...

    def list_work(
        self,
        *,
        session_id: str,
        owner_key: str,
        status: str | None = None,
        include_archived: bool = False,
        limit: int = 50,
        offset: int = 0,
    ) -> list[WorkItem]: ...

    def update_status(self, work_id: str, status: WorkStatus) -> WorkItem: ...

    def update_fields(self, work_id: str, *, title: str | None = None, description: str | None = None) -> WorkItem: ...

    def archive_work(self, work_id: str) -> WorkItem: ...

    def restore_work(self, work_id: str) -> WorkItem: ...

    def add_comment(self, comment: WorkComment) -> WorkComment: ...

    def list_comments(self, work_id: str, *, limit: int = 200, offset: int = 0) -> list[WorkComment]: ...

    def link_run(self, work_id: str, task_run_id: str, *, run_kind: str, status: str) -> WorkRunLink: ...

    def update_run_status(self, work_id: str, task_run_id: str, status: str) -> WorkRunLink: ...

    def list_runs(self, work_id: str, *, limit: int = 50, offset: int = 0) -> list[WorkRunLink]: ...

    def list_labels(self, session_id: str, *, owner_key: str) -> list[WorkLabel]: ...

    def set_label_links_by_names(self, work_id: str, *, session_id: str, owner_key: str, label_names: list[str]) -> list[str]: ...

    def inherit_parent_labels(self, work_id: str, parent_id: str) -> list[str]: ...

    def context_preview(self, work_id: str) -> dict[str, Any]: ...
